version: '2'
services:
#  web:
#    image: mandalae/yogalates
#    ports:
#      - 80:3000
#    links:
#        - "yogalates-db:yogalates-db"
#    environment:
#        - WEB_USER_PW
  yogalates-db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/Data/mongodb:/data/db
    command:
      - --auth
